on:
  push:
    branches:
      - main

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Checking success
    steps:
      - name: Test
        run: |
          echo ${{secrets.CRUST_SEEDS}}

  # test_job:
  #   runs-on: ubuntu-latest
  #   name: Testing on Crust IPFS uploader
  #   steps:
  #     - uses: actions/checkout@v2.1.0
  #     - name: Install dependencies
  #       run: npm install
  #     - name: Build
  #       run: npm run build
  #     - name: Crust IPFS uploader action
  #       id: pin
  #       uses: crustio/ipfs-upload-action@v2.0.2
  #       with:
  #         path: "./build"
  #         seeds: ${{ secrets.CRUST_SEEDS.CRUST_SEEDS }}
  #     - name: Upload success
  #       run: echo "Now, you can access with 'https://crustipfs.xyz/ipfs/${{ steps.pin.outputs.hash }}'"
